default_stages: [commit, push]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: pretty-format-json
        args: [--autofix]
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      args: [--line-length=120]
      language_version: python3.9
-   repo: local
    hooks:
        -   id: flake8
            name: Check flake8
            stages: [push]
            description: Flake8
            entry: flake8
            args: [local]
            language: script
            types: [python]
            pass_filenames: false
